# Generated by Django 3.0.6 on 2020-05-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='precio',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articulos',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
