# Generated by Django 3.0.6 on 2020-06-18 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MarketApp', '0002_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='market_id',
            new_name='market',
        ),
    ]
