# Generated by Django 3.0.6 on 2020-06-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketApp', '0006_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='History_Carts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCart', models.IntegerField()),
                ('nameProduct', models.CharField(max_length=30)),
                ('nameMarket', models.CharField(max_length=50)),
                ('priceProduct', models.FloatField()),
                ('priceTotal', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
