# Generated by Django 3.0.6 on 2020-06-25 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MarketApp', '0007_history_carts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history_carts',
            name='priceTotal',
        ),
    ]
