# Generated by Django 3.0.6 on 2020-07-02 17:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MarketApp', '0008_remove_history_carts_pricetotal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'cart'},
        ),
        migrations.AlterModelOptions(
            name='history_carts',
            options={'verbose_name': 'history_cart', 'verbose_name_plural': 'history_carts'},
        ),
        migrations.AlterModelOptions(
            name='markets',
            options={'verbose_name': 'market', 'verbose_name_plural': 'markets'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='markets',
            name='imagen',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='imagen',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
